---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "webservice"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "webservice"
    spec:
      containers:
      - name: "nginx"
        image: "nginx:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "webservice-scale"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "webservice"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 70